#!/bin/sh

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2019-2021 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-~aiplanner/aiplanner}
AIPLANNER_DATA=${AIPLANNER_DATA:-~aiplanner/aiplanner-data}
AI_DIR=$AIPLANNER_HOME/ai
API_DIR=$AI_DIR/docker/apiserver

ADMIN_EMAIL=`$AI_DIR/get_config admin_email`

if [ -e /etc/aliases.orig ]; then
    cp /etc/aliases.orig /etc/aliases
else
    cp /etc/aliases /etc/aliases.orig
fi

echo "aiplanner: root" >> /etc/aliases

if [ "$ADMIN_EMAIL" != None ]; then
    NOTIFY_EMAIL=`$AI_DIR/get_config notify_email "notify@aiplanner.com"`
    HOST=`echo $NOTIFY_EMAIL | sed 's/.*@//'`
    echo $HOST > /etc/mailname
    postconf -e "myhostname = $HOST"
    postconf -e "mynetworks ="
    echo "root: $ADMIN_EMAIL" >> /etc/aliases
else
    # Relay message to console.
    if ! chmod o+w /dev/console; then
        echo 'Try docker run -t ...'
        exit 1
    fi
    echo "root: /dev/console" >> /etc/aliases
fi
newaliases
# Need postfix running to relay message to console even if no admin.
service postfix start >/dev/null 2>&1

if [ ! -e $AIPLANER_DATA/market-data.json ]; then
    su -l aiplanner -c "cp $API_DIR/market-data.json $AIPLANNER_DATA"
fi

cron

su -l aiplanner -c "$API_DIR/start.aiplanner $@"

exit 1 # Inform docker of failure.
