#!/usr/bin/python

from os import environ
from sys import path

project = '/home/ubuntu/oaa/project'
if project not in path:
    path.append(project)

environ['DJANGO_SETTINGS_MODULE'] = 'settings'

from datetime import datetime
from time import time

from project.oaa.models import Account

for account in Account.objects.filter(temp_user=True):
    user = account.user
    if user.date_joined < datetime.utcfromtimestamp(time() - 86400):
        user.delete()
