#!/bin/bash

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018-2020 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}

. $AIPLANNER_HOME/ai/setenv

$AIPLANNER_HOME/ai/api/server.py "$@" &
