#!/bin/bash

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018-2021 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}

SERVER_RAY_ADDRESS=${SERVER_RAY_ADDRESS:-localhost:9736}

. $AIPLANNER_HOME/ai/setenv

ray start --num-cpus=1000 # CPU capacity controlled by aiplanner.yaml file, not by Ray.

$AIPLANNER_HOME/ai/api/server.py --address=$SERVER_RAY_ADDRESS "$@" &
