#!/bin/bash

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018-2019 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}

source $AIPLANNER_HOME/ai/helpers.bash

mkdir -p ~/aiplanner-data/models.new
cd ~/aiplanner-data/models.new

PARALLEL=Jobs

SAVESTEPS=2000000

TRAINING=generic
UNIT=single
STAGES="preretirement retired"
SPIAS_TYPES="none nominal"
GAMMAS="1.5 3 6"

for STAGE in $STAGES; do
    for SPIAS in $SPIAS_TYPES; do
        for GAMMA in $GAMMAS; do
            TIMESTEPS=`timesteps $TRAINING $UNIT $STAGE $SPIAS $GAMMA`
            ARGS="$TIMESTEPS --train-save-frequency=$SAVESTEPS"
            if ! skip_model $TRAINING $UNIT $STAGE $SPIAS $GAMMA; then
                train_scenarios $TRAINING $UNIT $STAGE $SPIAS $GAMMA "$ARGS"
            fi
        done
    done
done
wait

start_ray_if_needed
TEMPFILE=`tempfile -p train`
for MODEL_DIR in aiplanner-*.tf; do
    $AI_DIR/export_model.py --redis-address=$RAY_REDIS_ADDRESS --model-dir=$MODEL_DIR --train-seed=$SEED_START --train-seeds=$SEEDS >> $TEMPFILE 2>&1
done

cp $BASE_SCENARIO ./base-scenario.txt
echo '{}' > ./models-adjust.json
cp $AI_DIR/api/market-data.json ./
