#!/usr/bin/env python3

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2019 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

from os.path import expanduser
from sys import argv

from yaml import safe_load

def main():

    root_dir = expanduser('~/aiplanner-data')

    try:
        f = open('/aiplanner.yaml')
    except OSError:
        try:
            f = open(root_dir + '/aiplanner.yaml')
        except OSError:
            f = None
    config = safe_load(f) if f else {}

    print(config.get(argv[1]))

if __name__ == '__main__':
    main()
