#!/bin/sh

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018-2021 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}

AI_DIR=$AIPLANNER_HOME/ai

$AI_DIR/plot.py || exit 1
gnuplot ${AIPLANNER_FILE_PREFIX}-params.gnuplot $AI_DIR/plot.gnuplot || exit 1
