#!/usr/bin/env python3

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2019-2020 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

from sys import argv
from time import sleep

import ray

@ray.remote
def sleeper():
    while True:
          sleep(86400)

address = argv[1] if len(argv) > 1 else 'localhost:6379'

ray.init(address=address)

ray.get(sleeper.remote())
