#!/bin/sh

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2019 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}
AI_DIR=$AIPLANNER_HOME/ai

ARGS="$@"

CLUSTER=${CLUSTER:-$AI_DIR/cluster.yaml}

MODEL_DIR=aiplanner.tf
for ARG in "$@"; do
    case $ARG in
        --model-dir=*)
            MODEL_DIR=${ARG#*=}
            shift
            ;;
        --model-dir)
            MODEL_DIR="$2"
            shift
            shift
            ;;
    esac
done

case "$MODEL_DIR" in
    *.tf)
        rm -rf "$MODEL_DIR"
        ;;
    *)
        echo "Invalid model directory: $MODEL_DIR" >&2
        exit 1
        ;;
esac

CLUSTER_MODEL_DIR="/tmp/model_dir.$$.tf"
ray exec $CLUSTER "$AI_DIR/train_rllib.py $ARGS --model-dir=$CLUSTER_MODEL_DIR"
ray rsync_down $CLUSTER $CLUSTER_MODEL_DIR'/*' "$MODEL_DIR"
ray exec $CLUSTER "rm -r $CLUSTER_MODEL_DIR"
