#!/bin/sh

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018-2019 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}
AI_DIR=$AIPLANNER_HOME/ai

export CLASSPATH=$AIPLANNER_HOME/opal/classes/'*'
OPAL='java -ea com.gordoni.opal.OPAL'

validate () {

    MODEL_NAME=$1
    ARGS=$2

    MODEL_DIR=run.opal.$MODEL_NAME

    mkdir -p $MODEL_DIR
    $OPAL -c $AI_DIR/validation/opal-scenario3.txt -e "prefix='$MODEL_DIR/opal'" $ARGS 2>&1 | tee $MODEL_DIR/opal.log
}

validate run3-p_tax_free1000000 '-e start_tp=1000000'
