#!/bin/bash

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}
PARALLEL=${PARALLEL:-True}  # Set to "False" to run seeds sequentially rather than in parallel.
SEEDS=${SEEDS:-10}
if [ -n "$EVAL_NUM_TIMESTEPS" ]; then
    EXTRA_EVAL_ARGS="--eval-num-timesteps $EVAL_NUM_TIMESTEPS"
fi

EXTRA_ARGS=$*
AI_DIR=$AIPLANNER_HOME/ai
PYTHONPATH_ADD=$AI_DIR/baselines:$AI_DIR/gym-fin:$AIPLANNER_HOME/spia
if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH=$PYTHONPATH_ADD
else
    export PYTHONPATH=$PYTHONPATH_ADD:$PYTHONPATH
fi
CONFIG_FILE=$AI_DIR/validation/aiplanner-scenario.txt

if [ "$PARALLEL" = True ]; then
    VALIDATE=validate_parallel
else
    VALIDATE=validate
fi

validate () {

    MODEL_NAME=$1
    ARGS=$2
    TRAIN_ARGS=$3
    EVAL_ARGS=$4

    SEED=0
    set -o pipefail
    while [ $SEED -lt $SEEDS ]; do
        MODEL_DIR=run.ai.$MODEL_NAME-seed_$SEED.tf
        TEMPFILE=`tempfile -p valid`
        $AI_DIR/train_ppo1.py -c $CONFIG_FILE --model-dir=$MODEL_DIR $ARGS --train-seed=$SEED $TRAIN_ARGS $EXTRA_ARGS 2>&1 | tee -a $TEMPFILE || exit 1
        mv $TEMPFILE $MODEL_DIR/train.log
        $AI_DIR/eval_model.py -c $CONFIG_FILE --model-dir=$MODEL_DIR $ARGS $EVAL_ARGS $EXTRA_ARGS $EXTRA_EVAL_ARGS 2>&1 | tee $MODEL_DIR/eval.log || exit 1
        SEED=`expr $SEED + 1`
    done
}

validate_parallel () {

    MODEL_NAME=$1
    ARGS=$2
    TRAIN_ARGS=$3
    EVAL_ARGS=$4

    SEED=0
    while [ $SEED -lt $SEEDS ]; do
        MODEL_DIR=run.ai.$MODEL_NAME-seed_$SEED.tf
        # Output directory must not exist when tensorflow save() is called to save the model hence we can't write the log within it; instead log to a tempfile.
        TEMPFILE=`tempfile -p valid`
        TEMPFILES[$SEED]=$TEMPFILE
        $AI_DIR/train_ppo1.py -c $CONFIG_FILE --model-dir=$MODEL_DIR $ARGS --train-seed=$SEED $TRAIN_ARGS $EXTRA_ARGS > $TEMPFILE 2>&1 &
        SEED=`expr $SEED + 1`
    done
    wait

    SEED=0
    while [ $SEED -lt $SEEDS ]; do
        MODEL_DIR=run.ai.$MODEL_NAME-seed_$SEED.tf
        mv ${TEMPFILES[$SEED]} $MODEL_DIR/train.log
        $AI_DIR/eval_model.py -c $CONFIG_FILE --model-dir=$MODEL_DIR $ARGS $EVAL_ARGS $EXTRA_ARGS $EXTRA_EVAL_ARGS > $MODEL_DIR/eval.log 2>&1 &
        SEED=`expr $SEED + 1`
    done
    wait
}

$VALIDATE fixed_30-gi_0-no_bonds '--master-life-table=fixed --master-age-end=95 --master-gi-real=0 --master-no-real-bonds --master-no-nominal-bonds --master-bills'

$VALIDATE ssa_plus_3_female-iid_bonds '--master-no-real-bonds --master-no-nominal-bonds --master-iid-bonds'
$VALIDATE ssa_female-iid_bonds-static_real_spias '--master-life-expectancy-additional=0 --master-no-real-bonds --master-no-nominal-bonds --master-iid-bonds --master-static-bonds --master-real-spias'

$VALIDATE ssa_plus_3_female-nominal_5_bonds-nominal_spias '--master-no-real-bonds --master-nominal-bonds-duration=5 --master-nominal-spias'

$VALIDATE ssa_plus_3_female-real_5_bonds '--master-no-nominal-bonds --master-real-bonds-duration=5'
$VALIDATE ssa_plus_3_female-real_15_bonds '--master-no-nominal-bonds --master-real-bonds-duration=15'
$VALIDATE ssa_plus_3_female-real_bonds '--master-no-nominal-bonds'
$VALIDATE ssa_plus_3_female-nominal_1_bonds '--master-no-real-bonds --master-nominal-bonds-duration=1'
$VALIDATE ssa_plus_3_female-nominal_2_bonds '--master-no-real-bonds --master-nominal-bonds-duration=2'
$VALIDATE ssa_plus_3_female-nominal_5_bonds '--master-no-real-bonds --master-nominal-bonds-duration=5'
$VALIDATE ssa_plus_3_female-nominal_7_bonds '--master-no-real-bonds --master-nominal-bonds-duration=7'
$VALIDATE ssa_plus_3_female-nominal_10_bonds '--master-no-real-bonds --master-nominal-bonds-duration=10'
$VALIDATE ssa_plus_3_female-nominal_15_bonds '--master-no-real-bonds --master-nominal-bonds-duration=15'
$VALIDATE ssa_plus_3_female-nominal_20_bonds '--master-no-real-bonds --master-nominal-bonds-duration=20'
$VALIDATE ssa_plus_3_female-nominal_30_bonds '--master-no-real-bonds --master-nominal-bonds-duration=30'
$VALIDATE ssa_plus_3_female-nominal_bonds '--master-no-real-bonds'
$VALIDATE ssa_plus_3_female-real_and_nominal_bonds
$VALIDATE ssa_plus_3_female-iid_real_15_bonds '--master-no-real-bonds --master-no-nominal-bonds --master-iid-bonds --master-iid-bonds-type=real --master-iid-bonds-duration=15'
$VALIDATE ssa_plus_3_female-iid_nominal_15_bonds '--master-no-real-bonds --master-no-nominal-bonds --master-iid-bonds --master-iid-bonds-type=nominal --master-iid-bonds-duration=15'
$VALIDATE ssa_plus_3_female-real_and_nominal_bonds-interest_rate_blind '--master-no-observe-interest-rate'
$VALIDATE ssa_plus_3_female-real_and_nominal_bonds-inflation_rate_blind '--master-no-observe-inflation-rate'
$VALIDATE ssa_plus_3_female-real_and_nominal_bonds-blind '--master-no-observe-interest-rate --master-no-observe-inflation-rate'
$VALIDATE ssa_plus_3_female-real_and_nominal_bonds-real_spias '--master-real-spias'
$VALIDATE ssa_plus_3_female-real_and_nominal_bonds-nominal_spias '--master-nominal-spias'
$VALIDATE ssa_plus_3_female-real_and_nominal_bonds-real_and_nominal_spias '--master-real-spias --master-nominal-spias'

$VALIDATE spia-nominal_bonds-no_spias-couple '--master-no-stocks --master-no-real-bonds --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-nominal_bonds-nominal_spias-couple '--master-no-stocks --master-no-real-bonds --master-nominal-spias --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-nominal_bonds-nominal_spias_no_couple-couple '--master-no-stocks --master-no-real-bonds --master-nominal-spias --master-no-couple-spias --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-nominal_bonds-no_spias-single '--master-no-stocks --master-no-real-bonds'
$VALIDATE spia-nominal_bonds-nominal_spias-single '--master-no-stocks --master-no-real-bonds --master-nominal-spias'
$VALIDATE spia-stocks_and_nominal_bonds-no_spias-couple '--master-no-real-bonds --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-stocks_and_nominal_bonds-nominal_spias-couple '--master-no-real-bonds --master-nominal-spias --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-stocks_and_nominal_bonds-nominal_spias_no_couple-couple '--master-no-real-bonds --master-nominal-spias --master-no-couple-spias --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-stocks_and_nominal_bonds-no_spias-single '--master-no-real-bonds'
$VALIDATE spia-stocks_and_nominal_bonds-nominal_spias-single '--master-no-real-bonds --master-nominal-spias'
$VALIDATE spia-stocks_and_nominal_bonds-nominal_spias_80-couple '--master-no-real-bonds --master-nominal-spias --master-spias-age=80 --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-stocks_and_nominal_bonds-nominal_spias_80_no_couple-couple '--master-no-real-bonds --master-nominal-spias --master-spias-age=80 --master-no-couple-spias --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-stocks_and_nominal_bonds-nominal_spias_80-single '--master-no-real-bonds --master-nominal-spias --master-spias-age=80'
$VALIDATE spia-age80-stocks_and_nominal_bonds-no_spias-couple '--master-no-real-bonds --master-sex2=male --master-age-start=80 --master-age-start2=80 --master-p-tax-free=500000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-age80-stocks_and_nominal_bonds-nominal_spias-couple '--master-no-real-bonds --master-nominal-spias --master-sex2=male --master-age-start=80 --master-age-start2=80 --master-p-tax-free=500000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-age80-stocks_and_nominal_bonds-nominal_spias_no_couple-couple '--master-no-real-bonds --master-nominal-spias --master-no-couple-spias --master-sex2=male --master-age-start=80 --master-age-start2=80 --master-p-tax-free=500000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-age80-stocks_and_nominal_bonds-no_spias-single '--master-no-real-bonds --master-age-start=80  --master-p-tax-free=250000'
$VALIDATE spia-age80-stocks_and_nominal_bonds-nominal_spias-single '--master-no-real-bonds --master-nominal-spias --master-age-start=80 --master-p-tax-free=250000'
$VALIDATE spia-age90-stocks_and_nominal_bonds-no_spias-couple '--master-no-real-bonds --master-sex2=male --master-age-start=90 --master-age-start2=90 --master-p-tax-free=200000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-age90-stocks_and_nominal_bonds-nominal_spias-couple '--master-no-real-bonds --master-nominal-spias --master-sex2=male --master-age-start=90 --master-age-start2=90 --master-p-tax-free=200000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-age90-stocks_and_nominal_bonds-nominal_spias_no_couple-couple '--master-no-real-bonds --master-nominal-spias --master-no-couple-spias --master-sex2=male --master-age-start=90 --master-age-start2=90 --master-p-tax-free=200000 --master-gi-real2=16000' '--train-num-timesteps=5000000'
$VALIDATE spia-age90-stocks_and_nominal_bonds-no_spias-single '--master-no-real-bonds --master-age-start=90  --master-p-tax-free=100000'
$VALIDATE spia-age90-stocks_and_nominal_bonds-nominal_spias-single '--master-no-real-bonds --master-nominal-spias --master-age-start=90 --master-p-tax-free=100000'

# Notes on tweaks that have been tried out:
#
# train-reward-clip=50 produces worse results without guaranteed income, but had no effect when guranteed income was present.
#    $VALIDATE fixed_30-gi_0-p_300000-train_reward_clip_inf '--life-table=fixed --master-age-end=95 --master-guaranteed-income=0 --master-p-tax-free=300000' '--train-reward-clip=inf'
#    $VALIDATE fixed_30-gi_16000-p_2000000-train_reward_clip_inf '--life-table=fixed --master-age-end=95 --master-guaranteed-income=16000 --master-p-tax-free=2000000' '--train-reward-clip=inf'
#
# train-num-timesteps=4000000 doesn't improve CE:
#     $VALIDATE fixed_30-gi_16000-p_2000000-timesteps_4000000 '--life-table=fixed --master-age-end=95 --master-guaranteed-income=16000 --master-p-tax-free=2000000' '--train-num-timesteps=4000000'
#
# train-hidden-layer-size=96 doesn't improve CE:
#     $VALIDATE ssa_plus_3_female-real_and_nominal_bonds-train_hidden_layer_size_96 '' '--train-hidden-layer-size=96'
#
# May need to increase both hidden layer size and num timesteps together, but:
# train-hidden-layer-size=96 and train-num-timesteps=2000000 doesn't improve CE.
