#!/bin/sh

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018-2019 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}
AI_DIR=$AIPLANNER_HOME/ai

export CLASSPATH=$AIPLANNER_HOME/opal/classes/'*'
OPAL='java -ea com.gordoni.opal.OPAL'

mkdir -p ~/aiplanner-data/validation/run.opal.3
cd ~/aiplanner-data/validation/run.opal.3

validate () {

    MODEL_NAME=$1
    ARGS=$2

    MODEL_DIR=$MODEL_NAME

    mkdir -p $MODEL_DIR
    $OPAL -c $AI_DIR/validation/opal-scenario3.txt -e "prefix='$MODEL_DIR/opal'" $ARGS 2>&1 | tee $MODEL_DIR/opal.log
}

validate gamam3-tax_free250000 '-e utility_eta=3 -e start_tp=250000'
validate gamam3-tax_free500000 '-e utility_eta=3 -e start_tp=500000'
validate gamam3-tax_free1000000 '-e utility_eta=3 -e start_tp=1000000'
validate gamam3-tax_free2000000 '-e utility_eta=3 -e start_tp=2000000'
validate gamam6-tax_free250000 '-e utility_eta=6 -e start_tp=250000'
validate gamam6-tax_free500000 '-e utility_eta=6 -e start_tp=500000'
validate gamam6-tax_free1000000 '-e utility_eta=6 -e start_tp=1000000'
validate gamam6-tax_free2000000 '-e utility_eta=6 -e start_tp=2000000'

validate gamma3-preretirement '-e utility_eta=3 -e start_age=50'
validate gamma6-preretirement '-e utility_eta=6 -e start_age=50'
