#!/bin/bash

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}

source $AIPLANNER_HOME/ai/helpers.bash

CONFIG_FILE=$AI_DIR/validation/aiplanner-scenario2.txt
TRAIN_FILE=$AI_DIR/validation/aiplanner-scenario2.txt

run () {

    local MODEL_NAME=$1
    local ARGS=$2

    train $MODEL_NAME "--train-save-frequency=10000 $ARGS"
    evaluate $MODEL_NAME p_tax_free200000 "--eval-p-tax-free=200000 $ARGS"
    evaluate $MODEL_NAME p_tax_free1000000 "--eval-p-tax-free=1000000 $ARGS"
    # EVAL_ARGS='--eval-defined-benefits=[{"owner":"self","age":null,"probability":1.0,"payout":80e3,"source_of_funds":"tax_free"}]'
    # evaluate $MODEL_NAME defined_benefits_tax_free80000-p_tax_free1000000 "--eval-p-tax-free=1000000 $EVAL_ARGS $ARGS"

    EVAL_ARGS='--master-age-start=40 --master-life-expectancy-additional=3 --master-age-retirement=65 --master-defined-benefits=[{"owner":"self","age":null,"probability":1.0,"payout":16e3,"source_of_funds":"tax_free"}] --master-p_tax-deferred=0 --master-p_taxable-stocks=0 --master-p_taxable-iid_bonds=0'
    train $MODEL_NAME-p_tax_free200000 "--master-p-tax-free=200000 $EVAL_ARGS $ARGS"
    evaluate $MODEL_NAME-p_tax_free200000 p_tax_free200000 "--eval-p-tax-free=200000 $EVAL_ARGS $ARGS"
    train $MODEL_NAME-p_tax_free1000000 "--master-p-tax-free=1000000 $EVAL_ARGS $ARGS"
    evaluate $MODEL_NAME-p_tax_free1000000 p_tax_free1000000 "--eval-p-tax-free=1000000 $EVAL_ARGS $ARGS"

    SEED=0
    while [ $SEED -lt $SEEDS ]; do
        MODEL_DIR=aiplanner.$MODEL_NAME-seed_$SEED.tf
        $AI_DIR/extract_model.py -c aiplanner-scenario2.txt --model-dir=$MODEL_DIR $ARGS $EXTRA_ARGS --age-range 40 100 --num-age-steps=60 --p-type=tax_free \
            > $MODEL_DIR/extract.log 2>&1 &
        SEED=`expr $SEED + 1`
    done
    wait

    SEED=0
    while [ $SEED -lt $SEEDS ]; do
        MODEL_DIR=aiplanner.$MODEL_NAME-seed_$SEED.tf
        for AIPLANNER_LINEAR in $MODEL_DIR/aiplanner-linear*.csv; do
            export AIPLANNER_PREFIX=$MODEL_DIR/aiplanner
            export AIPLANNER_TIMESTEPS=`echo $AIPLANNER_LINEAR | sed 's/^.*-linear\([0-9]*\)\.csv$/\1/'`
            $AI_DIR/validation/plot2.gnuplot
        done
        convert -delay 5 -loop 0 $MODEL_DIR/aiplanner-consume[0-9]*.gif  $MODEL_DIR/aiplanner-consume-animated.gif
        convert -delay 5 -loop 0 $MODEL_DIR/aiplanner-stocks[0-9]*.gif  $MODEL_DIR/aiplanner-stocks-animated.gif
        SEED=`expr $SEED + 1`
    done
}

run ssa_40_plus_3_female-iid_bonds
run ssa_40_plus_3_female-iid_bonds-gamma6 '--master-gamma=6'
run ssa_40_plus_3_female-iid_bonds-stocks_return0.05 '--master-stocks-return=0.05'
