#!/bin/bash

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}
if [ -n "$EVAL_NUM_TIMESTEPS" ]; then
    EXTRA_EVAL_ARGS="--eval-num-timesteps $EVAL_NUM_TIMESTEPS"
fi

EXTRA_ARGS=$*
AI_DIR=$AIPLANNER_HOME/ai
PYTHONPATH_ADD=$AI_DIR/baselines:$AI_DIR/gym-fin:$AIPLANNER_HOME/spia
if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH=$PYTHONPATH_ADD
else
    export PYTHONPATH=$PYTHONPATH_ADD:$PYTHONPATH
fi
CONFIG_FILE=$AI_DIR/validation/aiplanner-scenario.conf

validate () {

    MODEL_NAME=$1
    MODE=$2
    ARGS=$3

    MODEL_DIR=run.$MODEL_NAME.$MODE
    mkdir -p $MODEL_DIR
    $AI_DIR/eval_model.py -c $CONFIG_FILE --$MODE $ARGS $EXTRA_ARGS $EXTRA_EVAL_ARGS 2>&1 | tee $MODEL_DIR/eval.log
}

validate fixed_30-gi_0-no_bonds merton '--master-life-table=fixed --master-age-end=95 --master-guaranteed-income=0'
validate fixed_30-gi_0-no_bonds samuelson '--master-life-table=fixed --master-age-end=95 --master-guaranteed-income=0'
