#!/bin/sh

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018-2019 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}
AI_DIR=$AIPLANNER_HOME/ai

export CLASSPATH=$AIPLANNER_HOME/opal/classes/'*'
OPAL='java -ea com.gordoni.opal.OPAL'

mkdir -p ~/aiplanner-data/validation/run.opal.4
cd ~/aiplanner-data/validation/run.opal.4

validate () {

    MODEL_NAME=$1
    ARGS=$2

    MODEL_DIR=$MODEL_NAME

    mkdir -p $MODEL_DIR
    $OPAL -c $AI_DIR/validation/opal-scenario4.txt -e "prefix='$MODEL_DIR/opal'" $ARGS 2>&1 | tee $MODEL_DIR/opal.log
}

for GAMMA in 1.5 3 5; do
    validate gamma$GAMMA-age50-tax_free2e5 "-e utility_eta=$GAMMA -e start_tp=200000"
    validate gamma$GAMMA-age50-tax_free5e5 "-e utility_eta=$GAMMA -e start_tp=500000"
    validate gamma$GAMMA-age50-tax_free1e6 "-e utility_eta=$GAMMA -e start_tp=1000000"
    validate gamma$GAMMA-age50-tax_free2e6 "-e utility_eta=$GAMMA -e start_tp=2000000"
    validate gamma$GAMMA-retired67-tax_free2e5 "-e birth_year=1953 -e start_age=67 -e utility_eta=$GAMMA -e start_tp=200000"
    validate gamma$GAMMA-retired67-tax_free5e5 "-e birth_year=1953 -e start_age=67 -e utility_eta=$GAMMA -e start_tp=500000"
    validate gamma$GAMMA-retired67-tax_free1e6 "-e birth_year=1953 -e start_age=67 -e utility_eta=$GAMMA -e start_tp=1000000"
    validate gamma$GAMMA-retired67-tax_free2e6 "-e birth_year=1953 -e start_age=67 -e utility_eta=$GAMMA -e start_tp=2000000"
    validate gamma$GAMMA-retired67-tax_free5e6 "-e birth_year=1953 -e start_age=67 -e utility_eta=$GAMMA -e start_tp=5000000"
done
