#!/bin/sh

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2019 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}
AI_DIR=$AIPLANNER_HOME/ai

. $AI_DIR/setenv

# Compute performance of fixed policy.
# Need to enable fixed policy in opal-scenario3.txt to compare.
ARGS="--master-stocks-mean-reversion-rate=0 --master-stocks-return=0.065 --master-stocks-volatility=0.174 --master-no-nominal-bonds --master-iid-bonds --master-iid-bonds-return=0.013 --master-iid-bonds-volatility=0.112 --master-no-returns-standard-error --master-no-tax"
ARGS="$ARGS --master-asset-allocation-policy='{"stocks":0.5,"iid_bonds":0.5}' --master-consume-policy=pmt"

../train_ppo1.py --model-dir=aiplanner.run3.tf --train-num-timesteps=1
../eval_model.py --model-dir=aiplanner.run3.tf $ARGS --master-age-start=65 --master-p-tax-deferred=1000000 --master-defined-benefits='[{"payout":16e3}]' --master-no-real-bonds --master-no-bills --master-gamma=6 --master-life-table=ssa-cohort --master-life-table-date=2020-01-01 --master-life-expectancy-additional=3 --eval-num-timesteps=2000000 | tee aiplanner.run3.tf/eval-p1000000.log
