#!/bin/bash

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018-2019 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}

source $AIPLANNER_HOME/ai/helpers.bash

BASE_ARGS="-c $AI_DIR/validation/aiplanner-scenario.txt"
TRAIN_ARGS="-c $AI_DIR/validation/aiplanner-scenario.txt"

validate () {

    local MODEL_NAME=$1
    local ARGS=$2
    local TRAIN_ARGS=$3
    local EVAL_ARGS=$4

    train $MODEL_NAME "$ARGS $TRAIN_ARGS"
    evaluate $MODEL_NAME "" "$ARGS $EVAL_ARGS"
}

validate fixed_30-gi_0-no_bonds '--master-life-table=fixed --master-age-end=95 --master-defined-benefits=[] --master-no-real-bonds --master-no-nominal-bonds --master-bills'

validate ssa_plus_3_female-iid_bonds '--master-no-real-bonds --master-no-nominal-bonds --master-iid-bonds'
validate ssa_female-iid_bonds-static_real_spias '--master-life-expectancy-additional=0 --master-no-real-bonds --master-no-nominal-bonds --master-iid-bonds --master-static-bonds --master-real-spias'

validate ssa_plus_3_female-nominal_5_bonds-nominal_spias '--master-no-real-bonds --master-nominal-bonds-duration=5 --master-nominal-spias'

validate ssa_plus_3_female-real_5_bonds '--master-no-nominal-bonds --master-real-bonds-duration=5'
validate ssa_plus_3_female-real_15_bonds '--master-no-nominal-bonds --master-real-bonds-duration=15'
validate ssa_plus_3_female-real_bonds '--master-no-nominal-bonds'
validate ssa_plus_3_female-nominal_1_bonds '--master-no-real-bonds --master-nominal-bonds-duration=1'
validate ssa_plus_3_female-nominal_2_bonds '--master-no-real-bonds --master-nominal-bonds-duration=2'
validate ssa_plus_3_female-nominal_5_bonds '--master-no-real-bonds --master-nominal-bonds-duration=5'
validate ssa_plus_3_female-nominal_7_bonds '--master-no-real-bonds --master-nominal-bonds-duration=7'
validate ssa_plus_3_female-nominal_10_bonds '--master-no-real-bonds --master-nominal-bonds-duration=10'
validate ssa_plus_3_female-nominal_15_bonds '--master-no-real-bonds --master-nominal-bonds-duration=15'
validate ssa_plus_3_female-nominal_20_bonds '--master-no-real-bonds --master-nominal-bonds-duration=20'
validate ssa_plus_3_female-nominal_30_bonds '--master-no-real-bonds --master-nominal-bonds-duration=30'
validate ssa_plus_3_female-nominal_bonds '--master-no-real-bonds'
validate ssa_plus_3_female-real_and_nominal_bonds
validate ssa_plus_3_female-iid_real_15_bonds '--master-no-real-bonds --master-no-nominal-bonds --master-iid-bonds --master-iid-bonds-type=real --master-iid-bonds-duration=15'
validate ssa_plus_3_female-iid_nominal_15_bonds '--master-no-real-bonds --master-no-nominal-bonds --master-iid-bonds --master-iid-bonds-type=nominal --master-iid-bonds-duration=15'
validate ssa_plus_3_female-real_and_nominal_bonds-interest_rate_blind '--master-no-observe-interest-rate'
validate ssa_plus_3_female-real_and_nominal_bonds-inflation_rate_blind '--master-no-observe-inflation-rate'
validate ssa_plus_3_female-real_and_nominal_bonds-blind '--master-no-observe-interest-rate --master-no-observe-inflation-rate'
validate ssa_plus_3_female-real_and_nominal_bonds-real_spias '--master-real-spias'
validate ssa_plus_3_female-real_and_nominal_bonds-nominal_spias '--master-nominal-spias'
validate ssa_plus_3_female-real_and_nominal_bonds-real_and_nominal_spias '--master-real-spias --master-nominal-spias'

validate spia-nominal_bonds-no_spias-couple '--master-no-stocks --master-no-real-bonds --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000'
validate spia-nominal_bonds-nominal_spias-couple '--master-no-stocks --master-no-real-bonds --master-nominal-spias --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000'
validate spia-nominal_bonds-nominal_spias_no_couple-couple '--master-no-stocks --master-no-real-bonds --master-nominal-spias --master-no-couple-spias --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000'
validate spia-nominal_bonds-no_spias-single '--master-no-stocks --master-no-real-bonds'
validate spia-nominal_bonds-nominal_spias-single '--master-no-stocks --master-no-real-bonds --master-nominal-spias'
validate spia-stocks_and_nominal_bonds-no_spias-couple '--master-no-real-bonds --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000'
validate spia-stocks_and_nominal_bonds-nominal_spias-couple '--master-no-real-bonds --master-nominal-spias --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000'
validate spia-stocks_and_nominal_bonds-nominal_spias_no_couple-couple '--master-no-real-bonds --master-nominal-spias --master-no-couple-spias --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000'
validate spia-stocks_and_nominal_bonds-no_spias-single '--master-no-real-bonds'
validate spia-stocks_and_nominal_bonds-nominal_spias-single '--master-no-real-bonds --master-nominal-spias'
validate spia-stocks_and_nominal_bonds-nominal_spias_80-couple '--master-no-real-bonds --master-nominal-spias --master-spias-age=80 --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000'
validate spia-stocks_and_nominal_bonds-nominal_spias_80_no_couple-couple '--master-no-real-bonds --master-nominal-spias --master-spias-age=80 --master-no-couple-spias --master-sex2=male --master-p-tax-free=1000000 --master-gi-real2=16000'
validate spia-stocks_and_nominal_bonds-nominal_spias_80-single '--master-no-real-bonds --master-nominal-spias --master-spias-age=80'
validate spia-age80-stocks_and_nominal_bonds-no_spias-couple '--master-no-real-bonds --master-sex2=male --master-age-start=80 --master-age-start2=80 --master-p-tax-free=500000 --master-gi-real2=16000'
validate spia-age80-stocks_and_nominal_bonds-nominal_spias-couple '--master-no-real-bonds --master-nominal-spias --master-sex2=male --master-age-start=80 --master-age-start2=80 --master-p-tax-free=500000 --master-gi-real2=16000'
validate spia-age80-stocks_and_nominal_bonds-nominal_spias_no_couple-couple '--master-no-real-bonds --master-nominal-spias --master-no-couple-spias --master-sex2=male --master-age-start=80 --master-age-start2=80 --master-p-tax-free=500000 --master-gi-real2=16000'
validate spia-age80-stocks_and_nominal_bonds-no_spias-single '--master-no-real-bonds --master-age-start=80  --master-p-tax-free=250000'
validate spia-age80-stocks_and_nominal_bonds-nominal_spias-single '--master-no-real-bonds --master-nominal-spias --master-age-start=80 --master-p-tax-free=250000'
validate spia-age90-stocks_and_nominal_bonds-no_spias-couple '--master-no-real-bonds --master-sex2=male --master-age-start=90 --master-age-start2=90 --master-p-tax-free=200000 --master-gi-real2=16000'
validate spia-age90-stocks_and_nominal_bonds-nominal_spias-couple '--master-no-real-bonds --master-nominal-spias --master-sex2=male --master-age-start=90 --master-age-start2=90 --master-p-tax-free=200000 --master-gi-real2=16000'
validate spia-age90-stocks_and_nominal_bonds-nominal_spias_no_couple-couple '--master-no-real-bonds --master-nominal-spias --master-no-couple-spias --master-sex2=male --master-age-start=90 --master-age-start2=90 --master-p-tax-free=200000 --master-gi-real2=16000'
validate spia-age90-stocks_and_nominal_bonds-no_spias-single '--master-no-real-bonds --master-age-start=90  --master-p-tax-free=100000'
validate spia-age90-stocks_and_nominal_bonds-nominal_spias-single '--master-no-real-bonds --master-nominal-spias --master-age-start=90 --master-p-tax-free=100000'

# Notes on tweaks that have been tried out:
#
# train-reward-clip=50 produces worse results without guaranteed income, but had no effect when guranteed income was present.
#    validate fixed_30-gi_0-p_300000-train_reward_clip_inf '--life-table=fixed --master-age-end=95 --master-guaranteed-income=0 --master-p-tax-free=300000' '--train-reward-clip=inf'
#    validate fixed_30-gi_16000-p_2000000-train_reward_clip_inf '--life-table=fixed --master-age-end=95 --master-guaranteed-income=16000 --master-p-tax-free=2000000' '--train-reward-clip=inf'
#
# train-single-num-timesteps=4000000 doesn't improve CE:
#     validate fixed_30-gi_16000-p_2000000-timesteps_4000000 '--life-table=fixed --master-age-end=95 --master-guaranteed-income=16000 --master-p-tax-free=2000000' '--train-single-num-timesteps=4000000'
#
# train-hidden-layer-size=96 doesn't improve CE:
#     validate ssa_plus_3_female-real_and_nominal_bonds-train_hidden_layer_size_96 '' '--train-hidden-layer-size=96'
#
# May need to increase both hidden layer size and num timesteps together, but:
# train-hidden-layer-size=96 and train-single-num-timesteps=2000000 doesn't improve CE.
