#!/bin/sh

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}

EXTRA_ARGS=$*
AI_DIR=$AIPLANNER_HOME/ai
export CLASSPATH=$AIPLANNER_HOME/opal/classes/'*'
OPAL='java -ea com.gordoni.opal.OPAL'

validate () {

    MODEL_NAME=$1
    ARGS=$2

    MODEL_DIR=run.$MODEL_NAME.opal

    mkdir -p $MODEL_DIR
    $OPAL -c $AI_DIR/validation/opal-scenario.txt -e "prefix='$MODEL_DIR/opal'" $ARGS $EXTRA_ARGS 2>&1 | tee $MODEL_DIR/opal.log
}

validate fixed_30-gi_0-p_500000-no_bonds "-e generate_life_table='fixed_mortality' -e validate_life_table='fixed_mortality' -e le_add=0 -e defined_benefit=0 -e start_tp=500000 -e asset_classes=('synthetic','risk_free2')"
validate ssa_plus_3_female-gi_16000-p_500000 "-e defined_benefit=16000 -e start_tp=500000"
