#!/bin/bash

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}
EVAL_TIMESTEPS=${EVAL_TIMESTEPS:-4000000}

AI_DIR=$AIPLANNER_HOME/ai
export PYTHONPATH=$AI_DIR/baselines:$AI_DIR/gym-fin

validate () {

    MODEL_NAME=$1
    MODE=$2
    ARGS=$3

    MODEL_DIR=run.$MODEL_NAME.$MODE
    mkdir -p $MODEL_DIR
    $AI_DIR/run_model.py --$MODE $ARGS --eval-num-timesteps=$EVAL_TIMESTEPS > $MODEL_DIR/eval.log 2>&1
}

validate fixed_30-gi_0-p_2000000 merton '--master-guaranteed-income=0 --master-p-notax=2000000'
validate fixed_30-gi_0-p_2000000 samuelson '--master-guaranteed-income=0 --master-p-notax=2000000'
