#!/bin/bash

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018-2019 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

source activate tensorflow_p36 # Doesn't belong here, but needed somewhere if want to start apiserver on system startup.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}

. $AIPLANNER_HOME/ai/setenv

$AIPLANNER_HOME/ai/web/server.py "$@"
