#!/bin/bash

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}

source $AIPLANNER_HOME/ai/helpers.bash

mkdir -p models
cd models

PARALLEL=Jobs

for UNIT in single couple; do

    for SPIAS in no_spias spias; do

        echo `date` Training $UNIT $SPIAS

        for GAMMA in 1 1.5 3 6; do

            ARGS="--master-gamma=$GAMMA"
            if [ $UNIT = couple ]; then
                ARGS="$ARGS --master-sex2=male"
            fi
            if [ $SPIAS = spias ]; then
                ARGS="$ARGS --master-nominal-spias"
            fi
            TIMESTEPS=`timesteps $UNIT $SPIAS`
            ARGS="$ARGS --train-num-timesteps=$TIMESTEPS"

            train $UNIT-$SPIAS-gamma$GAMMA $ARGS

        done
        wait
    done
done

echo `date` Done
