#!/bin/bash

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

AIPLANNER_HOME=${AIPLANNER_HOME:-$HOME/aiplanner}

source $AIPLANNER_HOME/ai/helpers.bash

mkdir -p models
cd models

PARALLEL=Jobs

GAMMAS="6 3 1.5 1"

echo `date` Training single no_spias
for GAMMA in $GAMMAS; do
    train single-no_spias-gamma$GAMMA "--master-gamma=$GAMMA"
done
wait

echo `date` Training single spias
for GAMMA in $GAMMAS; do
    train single-spias-gamma$GAMMA "--master-nominal-spias --master-gamma=$GAMMA"
done
wait

echo `date` Training couple no_spias
for GAMMA in $GAMMAS; do
    train couple-no_spias-gamma$GAMMA "--master-sex2=male --master-gamma=$GAMMA"
done
wait

echo `date` Training couple spias
for GAMMA in $GAMMAS; do
    train couple-spias-gamma$GAMMA "--master-sex2=male --master-nominal-spias --master-gamma=$GAMMA"
done
wait

echo `date` Done
