#!/bin/sh

# AIPlanner - Deep Learning Financial Planner
# Copyright (C) 2018 Gordon Irlam
#
# All rights reserved. This program may not be used, copied, modified,
# or redistributed without permission.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

if [ "$1" != "--model-dir" ]; then
    echo '--model-dir must be first argument' >&2
    exit 1
fi
MODEL_DIR=$2

TEMPFILE=`tempfile -p train`

STATUS=0
../train_ppo1.py $* > $TEMPFILE 2>&1 || STATUS=$?
mkdir -p $MODEL_DIR
mv $TEMPFILE "$MODEL_DIR/train.log" || STATUS=$?

exit $STATUS
